const PORTFOLIO_REVIEWS = [
  { name: 'Rahim K.', location: 'Dhaka', stars: 5, text: 'অসাধারণ কাজ! My store was live in 10 days. Admin panel টা খুব smooth। Highly recommend Nazmul bhai.', verified: true },
  { name: 'Sarah M.', location: 'Wyoming, USA', stars: 5, text: 'Professional and fast. He set up my LLC and Stripe within a week. Communication via WhatsApp was excellent.', verified: true },
  { name: 'Tanvir A.', location: 'Chittagong', stars: 5, text: 'SEO service নিয়েছিলাম — 2 সপ্তাহের মধ্যে Google এ rank করতে শুরু করেছে। Worth every dollar.', verified: true },
  { name: 'James L.', location: 'Texas, USA', stars: 5, text: 'Built my Shopify store from scratch. 50 products uploaded, payments working, looks premium. Will hire again.', verified: true },
  { name: 'Nusrat H.', location: 'Sylhet', stars: 5, text: 'Meta Ads campaign চালু করার পর sales 3x বেড়ে গেছে। ROAS optimization টা সত্যিই কাজ করে।', verified: true },
  { name: 'David P.', location: 'California', stars: 4, text: 'Good work on website speed. PageSpeed score went from 42 to 91. Minor delay on delivery but quality was solid.', verified: true },
  { name: 'Imran S.', location: 'Rajshahi', stars: 5, text: 'bKash আর COD দুটোই ঠিকমতো setup করেছে। Bangladesh store এর জন্য perfect developer।', verified: true },
  { name: 'Emily R.', location: 'New York', stars: 5, text: 'US LLC formation was seamless. Got all documents within 72 hours as promised. Very organized process.', verified: true },
  { name: 'Farhana B.', location: 'Dhaka', stars: 5, text: 'Product copywriting service নিয়েছিলাম — product description গুলো এত ভালো যে conversion rate বেড়েছে।', verified: true },
  { name: 'Michael T.', location: 'Florida', stars: 5, text: 'Amazon listing optimization was top-notch. My products started getting organic traffic within days.', verified: true },
  { name: 'Kamal U.', location: 'Khulna', stars: 5, text: 'AI chatbot বানিয়ে দিয়েছে store এ। Customer support এর load অনেক কমে গেছে। Genius idea!', verified: true },
  { name: 'Lisa W.', location: 'Ohio', stars: 5, text: 'Video editing quality is professional. Reels look amazing on Instagram. Fast turnaround too.', verified: true },
  { name: 'Arif M.', location: 'Barishal', stars: 5, text: 'পুরো e-commerce store build করেছে — design, payment, admin সব কিছু। একা সব handle করেছে, কোনো hassle নাই।', verified: true },
  { name: 'Robert K.', location: 'Michigan', stars: 4, text: 'Digital marketing campaign delivered good results. Would have liked more frequent updates, but ROI was positive.', verified: true },
  { name: 'Shamima R.', location: 'Comilla', stars: 5, text: 'Website speed fix এর পর mobile এ load time অর্ধেক হয়ে গেছে। Customer complaint ও কমেছে।', verified: true },
  { name: 'Chris B.', location: 'Arizona', stars: 5, text: 'PayPal and Stripe integration done perfectly. Test transactions passed, went live same day. Expert work.', verified: true },
  { name: 'Hasib N.', location: 'Gazipur', stars: 5, text: 'Shopify setup খুব professional। Theme customize, apps install, product upload — সব perfect।', verified: true },
  { name: 'Amanda J.', location: 'Georgia', stars: 5, text: 'Not just a developer — he understands business. Gave me strategy advice along with the website. Rare find.', verified: true },
  { name: 'Rakib I.', location: 'Mymensingh', stars: 5, text: 'SSLCommerz integration করেছে আমার BD store এ। Checkout flow smooth, customer happy।', verified: true },
  { name: 'Daniel F.', location: 'Colorado', stars: 5, text: 'Web app development exceeded expectations. React frontend is fast, admin panel is intuitive. 10/10.', verified: true },
  { name: 'Priya D.', location: 'Dhaka', stars: 5, text: 'Product copy আর SEO content লিখতে Nazmul ভাই অন্য level এর। Bangla + English দুটোই fluent।', verified: true },
  { name: 'Kevin H.', location: 'Nevada', stars: 4, text: 'Solid SEO work. Rankings improved for 8 of 10 target keywords. Still monitoring long-term results.', verified: true },
  { name: 'Sabbir T.', location: 'Rangpur', stars: 5, text: 'AI automation দিয়ে order notification auto হয়ে যায়। আগে manually করতাম, এখন সময় বাঁচে।', verified: true },
  { name: 'Jennifer C.', location: 'Washington', stars: 5, text: 'Meta Ads specialist who actually delivers. My cost per purchase dropped 40% after his optimization.', verified: true },
  { name: 'Mizan R.', location: 'Jessore', stars: 5, text: 'Video editing service নিয়ে খুব সন্তুষ্ট। Product showcase video দেখে অনেক customer order করেছে।', verified: true },
  { name: 'Thomas G.', location: 'Illinois', stars: 5, text: 'E-commerce store build was comprehensive. Policies, FAQ, admin — everything included. Launch-ready.', verified: true },
  { name: 'Lamia S.', location: 'Narayanganj', stars: 5, text: 'অনেক developer দেখেছি, কিন্তু Nazmul actually নিজের store চালায়। Real experience আছে, theory না।', verified: true },
  { name: 'William A.', location: 'Oregon', stars: 5, text: 'US LLC + payment gateway combo package was exactly what I needed to start selling online in America.', verified: true },
  { name: 'Jahanara K.', location: 'Bogura', stars: 5, text: 'Digital marketing strategy দিয়েছে যেটা follow করলে sales বাড়ে। Practical advice, not fluff।', verified: true },
  { name: 'Andrew D.', location: 'Pennsylvania', stars: 5, text: 'Hired for Amazon business setup. Listings are optimized, seller account verified. Professional from start to finish.', verified: true }
];